#生产环境配置
server:
  port: 80
springdoc:
  api-docs:
    enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  mail:
    host: smtp.163.com
    username: 15208403453@163.com
    password: VHFNZQSWNLYZUECX
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: h(urlLbnq6tw
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghi'
      expire: 1000
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  weather:
    key: 00f2cab7f504450491f8dce9c572344c
  minio:
    endpoint: 'http://192.168.1.106:9000'
    username: 'minioadmin'
    password: 'minioadmin'
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 10
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
